### ISSUE TITLE
Really low contrast for console output

### ISSUE THREAD

**Issue by paulvt** [Jorg3Lucas/jenkins-modern-themes#62]
If I look at the CSS it should be #e9eded on #0c0c0c, but it doesn't turn out that way?
It is hardly readable unfortunately.

![Screenshot from 2022-04-29 09-55-10](https://user-images.githubusercontent.com/551904/165905522-29bed94e-001d-415a-9413-2c90a6ec627b.png)

**Comment by greenflowers** [comment]
I can confirm the issue. I could fixed that by changing: 

`console-output pre{position:relative;font-family:Roboto Mono,Menlo,monospace!important;font-size:12px;background:#0c0c0c;color:#ffffff!important;cursor:text}`

**Comment by AirOnSkin** [comment]
Can confirm as well. I added the following extra CSS:
`pre {color: #bbbbbb !important}`

**Comment by offa** [comment]
PR to fix this: #71

**Comment by offa** [comment]
The script console is affected too. It seems to use other CSS settings though.

**Comment by ghost** [comment]
@offa @Jorg3Lucas can you confirm that this fix is deployed and working properly? we still have very low contrast

**Comment by offa** [comment]
Wired, the PR has been merged, but the changes got lost somehow!?

**Comment by ghost** [comment]
Seems like it. For now i am overwriting this specific part with an additional css text entry in jenkins:
```css
.console-output, .console-output pre {
  position: relative;
  font-family: Roboto Mono,Menlo,monospace!important;
  font-size: 12px;
  background: #0c0c0c;
  color: #e9eded !important;
  cursor: text;
}
```
but to me it seems as this issue is not closed :/
